apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cats-dogs.fullname" . }}
  labels:
    {{- include "cats-dogs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cats-dogs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cats-dogs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: FLASK_APP
              value: /app/main.py
          args:
            - flask
            - run
            - --host=0.0.0.0
            - --port=5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
