{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cats-dogs.fullname" . }}
  labels:
    {{- include "cats-dogs.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cats-dogs.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 80
          protocol: TCP
  egress:
    - {}
{{- end }}