{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cats-dogs.fullname" . }}
  labels:
    {{- include "cats-dogs.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "cats-dogs.selectorLabels" . | nindent 6 }}
{{- end }}